ktor:
  deployment:
    port: 8080
  application:
    modules:
      - plugin.ExposedKt.configureExposed
      - plugin.DIKt.configureDependencyInjection
      - RoutingKt.configureRouting
      - plugin.SerializationKt.configureSerialization
      - plugin.StatusPagesKt.configureStatusPages
