REVOKE USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA kilometer_tracker
FROM api;

REVOKE SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA kilometer_tracker
FROM api;

REVOKE USAGE ON SCHEMA kilometer_tracker FROM api;

REVOKE CONNECT ON DATABASE postgres FROM api;