CREATE ROLE api_admin NOLOGIN BYPASSRLS;

GRANT api_admin TO api;
ALTER ROLE api NOINHERIT;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kilometer_tracker TO api_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kilometer_tracker TO api_admin;