// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	Email  string
	Token  string
	Active bool
}

type User struct {
	Email     string
	Firstname pgtype.Text
	Lastname  pgtype.Text
	Status    pgtype.Text
}

type UserPassword struct {
	Email    string
	Password string
	Active   bool
}

type UserStatus struct {
	Status string
}
