// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package db

import (
	"context"
)

const disableRefreshToken = `-- name: DisableRefreshToken :exec
UPDATE refresh_token
SET active = false
WHERE token = $1
`

func (q *Queries) DisableRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, disableRefreshToken, token)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT email, token, active
FROM refresh_token
WHERE token = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(&i.Email, &i.Token, &i.Active)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_token (email, token, active)
VALUES ($1, $2, true)
`

type InsertRefreshTokenParams struct {
	Email string
	Token string
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.Email, arg.Token)
	return err
}
